name: my_app
description: Build using Vibe Studio
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: '>=3.22.3'

dependencies:
  gap: ^3.0.1
  intl: ^0.20.2
  file_picker: ^8.1.2
  equatable: ^2.0.5  
  flutter:
    sdk: flutter
  stacked: ^3.4.2    
  stacked_services: ^1.4.0
  logger: ^1.4.0
  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.3.0    
  sentry_flutter: ^7.18.0
  sentry_dart_plugin: ^2.4.1
  
  # Firebase Dependencies
  # Uncomment these lines when you need Firebase functionality
  # To use Firebase, you'll also need to:
  # 1. Create a Firebase project at https://console.firebase.google.com/
  # 2. Add your app to the Firebase project
  # 3. Download google-services.json and place it in android/app/
  # 4. Run 'flutterfire configure' to generate firebase_options.dart
  # 5. Uncomment the Firebase initialization in lib/main/bootstrap.dart
  # firebase_core: ^3.11.0
  # cloud_firestore: ^5.6.3
  # firebase_auth: ^5.4.2

dev_dependencies:
  build_runner: ^2.4.5
  flutter_lints: ^3.0.1  
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  json_serializable: ^6.8.0    
  mocktail: ^1.0.4
  stacked_generator: ^1.3.3  

flutter:
  uses-material-design: true
  generate: true


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/image.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/image.png"

sentry:
  project: my_app-6e0ca9
  org: okokl
  auth_token: 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
  upload_source_maps: true
  ignore_missing: true